<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_DosenSistem Informasi</name>
   <tag></tag>
   <elementGuidId>de378202-8635-4ef8-abda-a01e58d5fa59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='et-boc']/div/div/div[2]/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bfe2d1c5-3043-418a-9c42-d076ef068e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dosen Sistem Informasi</value>
      <webElementGuid>f3dcae72-76be-4bbb-8925-ef7a509d2135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et-boc&quot;)/div[@class=&quot;et_builder_inner_content et_pb_gutters3&quot;]/div[@class=&quot;et_pb_section et_pb_section_0 et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_1&quot;]/div[@class=&quot;et_pb_column et_pb_column_2_3 et_pb_column_1    et_pb_css_mix_blend_mode_passthrough&quot;]/div[@class=&quot;et_pb_module et_pb_text et_pb_text_0 et_pb_bg_layout_light  et_pb_text_align_left&quot;]/div[@class=&quot;et_pb_text_inner&quot;]/p[1]</value>
      <webElementGuid>ec175a4d-55b4-4fc0-b21b-7ca86f9ff900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et-boc']/div/div/div[2]/div/div/div/p</value>
      <webElementGuid>6b8011a3-3a4d-422c-92fb-b35e49ede729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wakil Dekan II Fakultas Teknologi Informasi'])[1]/following::p[1]</value>
      <webElementGuid>99183e32-8306-42eb-ad0f-704416f88c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Argo Wibowo, S.T., MT'])[2]/following::p[1]</value>
      <webElementGuid>e186c561-46fc-4ef7-aff2-d8f7b6f70a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>0ccf2505-8c6a-4518-89fb-ce998b152dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Dosen Sistem Informasi' or . = 'Dosen Sistem Informasi')]</value>
      <webElementGuid>de35c023-e0ed-49f0-b779-2005e45abcaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
