<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sistem Informasi</name>
   <tag></tag>
   <elementGuidId>1d5edf40-2763-4389-b914-c08ee7ca1487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-25814 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-25814']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f910ae69-34bd-4a76-9008-a3354ba11f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ukdw.ac.id/akademik/fakultas-teknologi-informasi/sistem-informasi/</value>
      <webElementGuid>ab13f0e1-b7c3-471a-88c8-71c55d118a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sistem Informasi</value>
      <webElementGuid>768abed6-e6ef-486b-b614-4bf093a5e0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-menu&quot;)/li[@id=&quot;menu-item-745&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@id=&quot;menu-item-798&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@id=&quot;menu-item-804&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@id=&quot;menu-item-25814&quot;]/a[1]</value>
      <webElementGuid>ca80fd30-8714-4906-a0a6-e49c03b7f636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-25814']/a</value>
      <webElementGuid>c44e4829-c910-46c6-9a21-fad2539467c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sistem Informasi')]</value>
      <webElementGuid>caaa1fad-b77c-4342-9b6f-bc50e1137e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informatika'])[1]/following::a[1]</value>
      <webElementGuid>d4d29633-721e-43eb-baa1-50c3d6019ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fakultas Teknologi Informasi'])[1]/following::a[3]</value>
      <webElementGuid>8592ba2b-bd39-46d5-8e59-5c29a4f4b9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fakultas Kedokteran'])[1]/preceding::a[1]</value>
      <webElementGuid>cb25146f-0ed5-40f0-8fe0-4bb54ba1aa9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kedokteran'])[1]/preceding::a[3]</value>
      <webElementGuid>5a46ee2f-3d0d-4ffa-b987-41057f1f18a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sistem Informasi']/parent::*</value>
      <webElementGuid>0e917b5a-3be9-4849-902b-8347ff8a1870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ukdw.ac.id/akademik/fakultas-teknologi-informasi/sistem-informasi/')]</value>
      <webElementGuid>f3d1ac51-d9d0-4761-a22e-2acb3ce84910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[5]/ul/li/ul/li[2]/a</value>
      <webElementGuid>8cd1bbda-49d9-45fd-be35-e1d186c70ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ukdw.ac.id/akademik/fakultas-teknologi-informasi/sistem-informasi/' and (text() = 'Sistem Informasi' or . = 'Sistem Informasi')]</value>
      <webElementGuid>a66c6ede-11fc-450d-a522-ff480b02dfd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
